### ISSUE TITLE
[Nox.Generators] Allow an Entity to have multiple relations to the same entity

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#656]
At the moment we do not support to multiple relations to the same entity, CryptoCashAPi has a good example in exchangerate entity:

![Image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/4ae8bb7c-8fdf-44ca-962b-f451626f88df)

in this example I suggest to start using the name, it will be unique and the generatedCode should be (this applies to all relations and not just multiple):

```
    /// <summary>
    /// ExchangeRate The currency exchanged from ExactlyOne Currencies
    /// </summary>
    public virtual Currency CurrencyFrom { get; set; } = null!;

    /// <summary>
    /// ExchangeRate The currency exchanged to
    /// </summary>
    public virtual Currency CurrencyTo { get; set; } = null!;
```

and we drop the navigation `public Currency CurrencyFrom => Currency;`

1.  Update Entity template
2. Update Entity Dto Template
3.  Update Database Configurator is needed
4. Create test on ClientApiTest with "real" example

**Comment by ILoveMyTortoise** [comment]
work on cryprot cash (not sample web app)
