### ISSUE TITLE
[Nox.Types] Remove DatabaseGuid MP-9144

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#719]
1. Remove this NoxType completely
3. Replace existing yaml in tests and samples by the Guid type
4. If a Guid is part of/ or key, on the EntityFactory generate and set the field, this will be the default behavior => Update EntityFactory.template.cs, override the CreateEntity  method call it and set the field with the new Guid

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9144
