### ISSUE TITLE
[Nox.Docs] Generate Documentation for EndPoints MP-9202

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#740]
# Prepare templates and markdown files
1. the current readme file can me moved/generated in    \.nox\docs (example https://github.com/NoxOrg/Nox.Generator/blob/main/samples/README.md)
2. 1. in \.nox\docs generate a \<EntityName\>EndPoints.md file for each entity (except owned entities) , that will be used to document all End Points (Use scriban) 
1. Update the current generated readme, add a link to each entity, for example:
 
![Image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/81cf0e36-e58c-4524-bd1d-3f01acb199af)
***
#  Generate the content for the End Points
1. Create a Section for Entity, a section for Owned Relations,section for Relations a section for Custom Commands a section for Custom Queries
2. All with subsection for each verb Get/Post/.. 
3. Generate a summary a a relative path for each end point

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9202

**Comment by gjorgji-grgovski-authoritypartners** [comment]
Hi @Mornevanzyl, can you please help out defining the Markdown for the Readme.md documentation for the Endpoints?

This is my suggestion, but let me knwo if you see it differently.

`# API Endpoints

This document provides information about the various endpoints available in our API.

## Entity Endpoints

### Get Entity
- **GET** `/api/entities/{id}`
  - Description: Retrieve information about a specific entity by ID.
  
### Create Entity
- **POST** `/api/entities`
  - Description: Create a new entity with the provided data.
  
### Update Entity
- **PUT** `/api/entities/{id}`
  - Description: Update an existing entity by ID with the provided data.
  
### Delete Entity
- **DELETE** `/api/entities/{id}`
  - Description: Delete an entity by its ID.

## Owned Relations Endpoints

### Get Owned Relations
- **GET** `/api/owned-relations/{entity_id}`
  - Description: Retrieve all owned relations for a specific entity.
  
### Create Owned Relation
- **POST** `/api/owned-relations/{entity_id}`
  - Description: Create a new owned relation for a specific entity.
  
### Update Owned Relation
- **PUT** `/api/owned-relations/{entity_id}/{relation_id}`
  - Description: Update an existing owned relation for a specific entity.
  
### Delete Owned Relation
- **DELETE** `/api/owned-relations/{entity_id}/{relation_id}`
  - Description: Delete an owned relation by its ID.

## Relations Endpoints

### Get Relations
- **GET** `/api/relations/{entity_id}`
  - Description: Retrieve all relations for a specific entity.
  
### Create Relation
- **POST** `/api/relations/{entity_id}`
  - Description: Create a new relation for a specific entity.
  
### Update Relation
- **PUT** `/api/relations/{entity_id}/{relation_id}`
  - Description: Update an existing relation for a specific entity.
  
### Delete Relation
- **DELETE** `/api/relations/{entity_id}/{relation_id}`
  - Description: Delete a relation by its ID.

## Custom Commands Endpoints

### Execute Custom Command
- **POST** `/api/custom-commands`
  - Description: Execute a custom command with the provided parameters.

## Custom Queries Endpoints

### Execute Custom Query
- **POST** `/api/custom-queries`
  - Description: Execute a custom query with the provided parameters.

`
CC: @rochar @nagykarim @dejobratic
