### ISSUE TITLE
[Nox.Generators] Generate Domain Events (records) to the EntityGenerator

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#760]
1. Rename contract INoxDomainEvent to IDomainEvent in Nox.Abstractions, keep consistent with others
2. Update the Entity Generator and generate the Dto for the Domain events, (Consider only what is set at the Entity.Persistence.Create.RaiseEvents and IsEnabled). The event will carrier the entity state. expected generated code:

![Image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/5f80cff1-6d30-42da-ad90-5bd8e3258261)

related to #755

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9223
