### ISSUE TITLE
[Nox.Generators] Dispatch Domain Events before Saving to the db - MP-9237

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#767]
For the <Service>DbContext, generated code:

1. Override db context savechangesasync to raise the  RaiseCreateEvent();  or RaiseDeleteEvent(); or RaiseUpdateEvent(); according to the type of change, dispatch all events and call  ClearDomainEvents();

3. After the Audit Part, and before the Saving
4.  Call RaiseDefaultDomainEvents  and Dispatch the events asynchronously
   ![image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/93045420-48c1-4bce-ae35-366f0631fe66)
5. Use MediatR INotification to Dispatch and subscrive them
6. USe ServiceCollection Extension, AddNoxMediatR method to register all Notification Handlers see for example the 
7. Create a "real" example on ClientAPi Tests how to subscribe the Notification  and do some custom logic

relates to #755 depends on #761

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9237

**Comment by gjorgji-grgovski-authoritypartners** [comment]
@rochar we might need to introduce a new flag on the IDomainEvent


```
    /// <summary>
    /// Gets or sets a value indicating whether this domain event is published.
    /// </summary>
    public bool IsPublished { get; set; }
```

This would be needed in order to avoid duplicating the sending of the Domain events, for instance, if we have AggregateRoot and its Relationship.
Lets discuss this.

**Comment by gjorgji-grgovski-authoritypartners** [comment]
@rochar let's discuss also this thing because we would have to distinguish when the State is Added/Modified/Deleted
```
private void AddAndDispatch(EntityEntry<IEntityHaveDomainEvents> entry)
{
    switch (entry.State)
    {
        case EntityState.Added:
            entry.Entity.RaiseDefaultCreatedDomainEvents(entry.Entity);
            break;

        case EntityState.Modified:
            entry.Entity.RaiseDefaultUpdatedDomainEvents(entry.Entity);
            break;

        case EntityState.Deleted:
            entry.Entity.RaiseDefaultDeletedDomainEvents(entry.Entity);
            break;
    }


    await DispatchEvents(entry.Entity.Events);
}
```
