### ISSUE TITLE
[Nox.Generators] Generate Documentation for Entity Events

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#768]

**Comment by rochar** [comment]
# Prepare templates and markdown files
1. in \.nox\docs generate a \<EntityName\>EndPoints.md file for each entity (except owned entities) , that will be used to document all End Points (Use scriban) 
1. the current readme file can me moved/generated in    \.nox\docs (example https://github.com/NoxOrg/Nox.Generator/blob/main/samples/README.md)
1. Update the current generated readme, add a link to each entity, for example:
 
![Image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/81cf0e36-e58c-4524-bd1d-3f01acb199af)
***
#  Generate the content for the End Points
1. Create a Section for Entity, a section for Owned Relations,section for Relations a section for Custom Commands a section for Custom Queries
2. All with subsection for each verb Get/Post/.. 
3. Generate a summary a a relative path for each end point

**Comment by gjorgji-grgovski-authoritypartners** [comment]
Hi @Mornevanzyl , can you please help define the Markdown for the Readme.md documentation for the Domain Events?

This is my suggestion, but let me know if you see it differently.

`# Domain Events

This document provides information about the Domain Events in our application.

## Events

### `WorkplaceCreated`

- **Description:** This event is triggered when a new workplace is created in the system.
- **Attributes:**
  - `workplaceId` (string): The unique identifier of the newly created workplace.
  - `name` (string): The name of the workplace.
  - `createdAt` (timestamp): The timestamp when the workplace was created.

### `WorkplaceUpdated`

- **Description:** This event is triggered when an existing workplace is updated in the system.
- **Attributes:**
  - `workplaceId` (string): The unique identifier of the updated workplace.
  - `name` (string): The new name of the workplace.
  - `updatedAt` (timestamp): The timestamp when the workplace was last updated.

### `WorkplaceDeleted`

- **Description:** This event is triggered when a workplace is deleted from the system.
- **Attributes:**
  - `workplaceId` (string): The unique identifier of the deleted workplace.
  - `deletedAt` (timestamp): The timestamp when the workplace was deleted
`
CC: @rochar @nagykarim @dejobratic
