### ISSUE TITLE
[Nox.Generators] Create endpoints for single Owned Entity (without relatedKey) like multiple

### ISSUE THREAD

**Issue by anna-naumova25** [NoxOrg/Nox#772]

**Comment by rochar** [comment]
we are going to refactor Entity Mapper... lets keep an eye on it so we do not have many conflicts

**Comment by rochar** [comment]
@anna-naumova25  if you look to the StoresController, the ownedEntity VerifiedEmails is not having endpoints generated (Get(all, and by related key)/Post/Put/Patch), is this what you mean?
