### ISSUE TITLE
[Nox.Generator]  Get Related Entity by relatedkey

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#782]
related to #776, depends on #571

## Get Related Entities via Parent
/{entityset}/{key}/{navigationproperty}/$ref
returns a \<RelatedEntityDto\> single or IQueryable. Add Odata Query support for IQueryable/Collections using EnableQuery

**Comment by anna-naumova25** [comment]
/{entityset}/{key}/{navigationproperty}/$ref

For a single-valued navigation property, the response is an entity reference pointing to the related single entity.
For a collection-valued navigation property, the response is a collection of entity references pointing to the related entities.
