### ISSUE TITLE
[Nox.Generators] EndPoints for Owned and Relations considerer IsEnabled on Persistence MP-9289

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#791]
The entity Persistence define what endpoints should be created:
![image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/d5d49653-be96-4c83-91e9-7339e79df75b)

So we need considerer them when:
1. Generating Owned Entities EndPoints
2. Generating RelationShip EndPoints (depends on #570 )
1. The generated documentation for the end points should consider this

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9289

**Comment by nagykarim** [comment]
moving to Blocked - pending Issue #776

**Comment by anna-naumova25** [comment]
@nagykarim @dejobratic @gjorgji-grgovski-authoritypartners 
All the tickets related to the Relationships are now closed and merged to main. So the Relationships can now be documented in the same way as Owned Entities. Please let me know if you have any questions about it and feel free to reach me out in Teams (anna.naumova@iwgplc.com).

@rochar FYI
