### ISSUE TITLE
[Nox.Solution] OwnedEntity Validation - Can not have Relationships MP-9270

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#792]
Add a new validation to Nox.Solution:

An OwnedEntity (exists in an second Entity  OwnedRelationships) can not have have a relationship to a second Entity (cannot have Relationships), because the Owned Entity it will not be treated as an Entity

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9270
