### ISSUE TITLE
[Nox.Type] Change LatLong Persistance type MP-9310

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#812]
At the moment we are persistence Lat long as two doubles , and is a compoundtype / owned in EF

We need to do the following changes:

1. Change to SimpleType, underlinetype is NetTopologySuite.Geometries.Point
2. change database configuration example (for postgres, mssql and sqlite):
 
```
    options.UseSqlServer(
       @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=WideWorldImporters",
      x => x.UseNetTopologySuite());

        optionsBuilder.UseNpgsql(
            @"Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase",
            o => o.UseNetTopologySuite());
            
```
1. NoxType Value Type must be NetTopologySuite.Geometries.Point
1. We should not need a converter
1. Reconfigure ODataServiceCollection and add:

```
var point = oDataBuilder.ComplexType<NetTopologySuite.Geometries.Point>();
point.Property(p => p.X);
point.Property(p => p.Y);
point.Ignore(p => p.Z);
point.Ignore(p => p.M);
point.Ignore(p => p.NumPoints);
point.Ignore(p => p.Area);
point.Ignore(p => p.CoordinateSequence);
point.Ignore(p => p.Coordinates);
point.Ignore(p => p.UserData);
point.Ignore(p => p.SRID);
```
1. Build a filter `LatLonSchemaFilter:ISchemaFilter` and for Point just make the X and Y available and ignore all others (https://stackoverflow.com/posts/54480742/revisions), for now each service can use the filter to customize swagger if needed

1. Build some tests in ClientApi and Nox.Integration.Test

References:
https://learn.microsoft.com/en-us/ef/core/modeling/spatial
https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite
https://www.npgsql.org/efcore/mapping/nts.html?tabs=with-datasource
https://learn.microsoft.com/en-us/ef/core/providers/sqlite/spatial

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9310
