### ISSUE TITLE
[Nox.Solution] Entity Persistence Setting refactor RaiseEvents to be a enum type MP-9359

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#814]
Create a new enum RaiseEventsType, with options Never, DomainEventsOnly, DomainAndIntegrationEvents

Update:

1. EntityCreateSettings
2. EntityReadSettings
3. EntityUpdateSettings

change RaiseEvents from bool to RaiseEventsType. 

work with @Mornevanzyl  to update documentation

**Comment by dejobratic** [comment]
Hi @Mornevanzyl 
Can you confirm whether we would require some documentation changes after the changes for raising events?
There is an opened PR linked to this ticket. Feel free to reach out to me if you need more info.

cc @gjorgji-grgovski-authoritypartners @rochar
