### ISSUE TITLE
[Nox.Generator] Generate Custom Integration Event - MP-9366

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#820]
- relates to #799 
# Custom Integration  Event

1. Deprecate ApplicationEventGenerator and create a template, NoxGeneratorKind.Domain, for generating the IE in Nox.Generator.Application.IntegrationEvents namespace
1. Add the template to Nox.Generator.Application.IntegrationEvents
1. Although the attributes are Nox.Types we need to generate as primitive types as we do for dtos
    1. For compound types use the already existing dtos
1. generated file name \<Service\>.Application.IntegrationEvents.\<IntegrationEvent\>.g.cs
1. The event inherits from IIntegrationEvent and contains all the properties defined in the yaml 
2. create an example and test on Client API test how to raise a Custom IE, by subscribing a DomainEvent and raising it on the handler using IMessageOutbox (when done send this information to @Mornevanzyl to be added to the documentation Extending Nox)

**Comment by gjorgji-grgovski-authoritypartners** [comment]
@rochar point 5 is blocked by #767, do we want to maybe raise the Integration Event for now from the CommandHandlers, or would we wait for the implementation of the #767 ?

CC: @dejobratic
