### ISSUE TITLE
[Nox.Generator] Generate Default Integration Events

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#821]
- relates to #799 
- depends on #820 

1. reuse the Custom IE template, get the attributes from the relate Domain Event
1. generate IE only when  Entity Persistence RaiseEvents is DomainAndIntegrationEvents
1. Create a template to generate a Notification Handler to consume the DomainEvent and add the IE  to the MessagesOutbox
1. Add the template to Nox.Generator.Application.NotificationHandlers
1. generated  file name \<Service\>.Application.NotificationHandlers.\<DomainEventHandler\>.g.cs
2. create an example on Client API (Yaml), so a IE is generated (when done send this information to @Mornevanzyl  to be added to the documentation Extending Nox)

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9464
