### ISSUE TITLE
[Nox.Docs] Documentation for Integration Events MP-9440

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#822]
depends on #820 and #821

# Documentation 
1. Add to readme a link to Integration  Events generate a new markdown page to list the events in ./nox/docs/IntegrationEvents.md , describe it has we do for the Domain Events (attributes, etc...)
3. List the Custom IE and the Generated IE , grouped by Topic Name (section) (TODO link Topic name)
![image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/94436c0d-677c-4634-969c-280d53ad4e06)
(in the image consider Integration Event instead of Application Event)

@Mornevanzyl  we will need a Section for Domain Events (in the context of this issue #755 ) and One For Integration Events
In the Integration Event we need to provide the envelope that will carry each of the event, see https://cloudevents.io/ for specification, example:

```
{
	"specversion": "1.0",									
	"id": "5e39aa3b-1572-4f03-8ebc-89fed412cbf8", 				
	"source": "https://cryptocash.com/cryptocashapi",  			
	"type": "cryptocash.samples.vendingmachines.v1.0.created",			
	"datacontenttype": "application/json",						
	"dataschema": "https://cryptocash.com/schemas/samples/vendingmachines/v1/created.json"
	"time": "2023-05-19T11:09:57.7530346Z",						
	"xtenantid": "4c1f190a-b6e9-4c0f-98bf-1cf0921f35a0",		
	"xuserid": "user@mail.com",									
	"data": {
            "vendingmachineId": "c19d5166-978a-4f00-9e6a-fc0ff4f7ae63"
       }
}
```

**Comment by rochar** [comment]
depends on #820 and #821

1. Add to readme a link to Integration  Events generate a new markdown page to list the events in ./nox/docs/IntegrationEvents.md  
3. List the Custom IE and the Generated IE 
![image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/94436c0d-677c-4634-969c-280d53ad4e06)
(in the image consider Integration Event instead of Application Event)

Work with @Mornevanzyl to add the necessary documentation and example to noxorg.dev

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9440
