### ISSUE TITLE
[Nox.Integration.Test] Fix test GeneratedEntity_Sqlite_CanSaveAndReadFields_AllTypes

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#835]
Fix test the GeneratedEntity_Sqlite_CanSaveAndReadFields_AllTypes 
[Fact(Skip = "NOT NULL constraint failed: TestEntityForTypes.AutoNumberTestField")]

**Comment by AndreyDegtyarev** [comment]
The issue is that Sqlite provider support field generation for keys, however it doesn't support for simple field. So GenerateValueOnAdd() doesn't make impact on column in db, then it gets error about trying to add null value in not nullable field.
