### ISSUE TITLE
[Nox.Generators] Create function on Entity Add/Delete Owned Entity MP-9447

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#839]
A Entity must updated using the proper function so its possible to add rules and extend the behavior, this should not be set directly in properties

1. Create functions in the Entity to manage Entity Owned Add/Delete
2. Update Factories to call this functions instead of setting the property directly
3. set owned navigation properties to private (used only by EF)

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9447
