### ISSUE TITLE
[Nox.Solution] Allows to have a single owned entity with a key

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#840]
Single owned entity can not have keys defined

A validation error should occur during compilated in the Generator

@dejobratic @anna-naumova25  can show you an example if needed

**Comment by anna-naumova25** [comment]
@dejobratic 
The same thing for multiple owned entity - it must have Keys defined

A validation error should occur during compilated in the Generator if Keys are not defined for ZeroOrMany/OneOrMany owned relationships.

Please see issue 1 and issue 4 in #611 for the details and feel free to reach me out if you have any questions.
