### ISSUE TITLE
[Nox.Ui] Cryptocash.Api problem POST on VendingMachine investigation task

### ISSUE THREAD

**Issue by DanielHodgeGH** [NoxOrg/Nox#894]
To investigate problem with POST vendingmachine through Cryptocash.Api - currently using swagger page directly to do post - says internal error

{
  "statusCode": 500,
  "message": "Error occured during request: /api/VendingMachines.Error: An error occurred while saving the entity changes. See the inner exception for details."
}

https://localhost:44310/api/VendingMachines

Minimal Info JSON that I was using to get it to work:

[minimalinfo_vendingmachine.zip](https://github.com/NoxOrg/Nox.Generator/files/12783111/minimalinfo_vendingmachine.zip)

**Comment by ILoveMyTortoise** [comment]
Not being reproduced anymore
