### ISSUE TITLE
[Nox.Generator] Domain Event method is invoked when raiseEvents: never is configured

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox#948]
I configure my currency entity as follows:
![image](https://github.com/NoxOrg/Nox.Generator/assets/64355398/3345bc91-a6fd-4658-869f-83cec1582703)
And get this build error:
![image](https://github.com/NoxOrg/Nox.Generator/assets/64355398/37a2adee-681d-451b-b989-4537f0560549)
From the source file, the internal record haven't been created (as expected since we configured events to 'never') but the CurrencyDeleted method is still called?
![image](https://github.com/NoxOrg/Nox.Generator/assets/64355398/bc6eb4cd-c2a2-43a3-82ad-28395be8cfa4)
![image](https://github.com/NoxOrg/Nox.Generator/assets/64355398/4099c7b3-2d9b-4f94-98fc-1a4434e0949b)

**Comment by rochar** [comment]
The method InternalRaiseDeleteEvent should be empty is this case

Ensure we have a test case for this

**Comment by rochar** [comment]
![image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/7c2a6df5-7b46-488d-9943-36d5ee390604)

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9592
