### ISSUE TITLE
[Nox.Generator] PartialUpdate<Entity>Command save to Localized table MP-9667

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#955]
- relates to #907 
- depends on #936 

## Task
1. In the API Patch, get the request language from the header, fall back to default language in Nox.Solution if not found, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language, see also #937
2. Change the Create\<Entity>Command request to accept a CultureCode  
3. Update the command to:
    1. Add new translations to <Entity>Localized Table
    2. Set the translation in the Entity Fields only if is the Default Culture Code Defined in Nox

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9667
