### ISSUE TITLE
[Nox.Generator] Get Entity Translations MP-9639

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#956]
- relates to #907 
- depends on #936 
- depends on #957

# End Point to get all translations for a Entity by Id

## Tasks 
1. Create a new template for adding the translations end points (see how the controllers templates are organized), generating a partial class in `Presentation.Api.Odata.<EntityPluralName>Controller.Translations.g.cs`
2. Add the following End Point:  GET `/api/<entity>/{key}/<Entity>Localized/` 
3. Add the following query `Application.Queries.Get<Entity>ByIdTranslations` in a new template
1. Returns `IQueryable<<Entity>LocalizedDto>`
2. EnableQuery for OData
3. Test the end point with Odata Select and filter for example
4. Register `<Entity>LocalizedDto>` in Odata Model
5. Check OData Metadata

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9639
