### ISSUE TITLE
[Nox.Generator] Localization Dto Data Model

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#957]
- relates to #907 
- relates to #936

# Dto Data Model

We will create an additional class model (EF) for each Entity that contains all localized fields, for example, for Country Entity, if the Description and ShortDescription are localized fields, then we will have:

```
  public class CountryLocalizedDto
  {    
      public int CountryId { get; set; } // Primary & Foreign key
      public string CultureCode { get; set; } // Primary Key
      public string Description { get; set; }
      public string ShortDescription { get; set; }
  }
```
## Tasks

1. Create a new template : \<Entity\>LocalizedDto
2. Generate a new Model, for All Entities that have at least one localized field (exclude owned entities)
3. In the EntityDto namespace
4. Add the Entity key  - {KeyNameId} (For now support only entities with single key)
5. Add the CultureCode Property (will be set as Primary Key with the Entity Foreign Key)
6. Add an attribute for each localized field, with the proper Nox.Type Primitive Type
7. Register the Dbset on the Dto DbContext
8. Configure the new entity in DtoDbcontext

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9632
