### ISSUE TITLE
[Nox.Generator] Create or Update Entity Translations

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#958]
- relates to #907 
- depends on #936 
- depends on #957

## Tasks 
1. on the  template   `Presentation.Api.Odata.<EntityPluralName>Controller.Translations.g.cs` add the following End Point:  Post and Put `/api/<entity>/{key}/<Entity>Localized/{culturecode}` 
2. Receives in the Body an `<Entity>LocalizedDto` with the new data (no need to an update dto), uses the Key as Id ignore the Dto Key
3. Add the following Commands `Application.Command.Update<Entity>Translations` and `Application.Command.Create<Entity>Translations` in a new template
   1. Update Localized Table
   2. Update Main Entity if if the Default Culture code 
1. Return single `<Entity>LocalizedDto>` following Odata Conventions
4. Register the Action in ODataModel if not recognized (see endpoints for owned entities for reference) (Non conventional end point) => in this case follow the naming convention for the method, for example conventional vs non conventional:

     ![Image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/008de667-ee02-4d68-8116-a896b12bd161)

5. Check OData Metadata

**Comment by gjorgji-grgovski-authoritypartners** [comment]
https://regusit.atlassian.net/browse/MP-9646
